import type { Metadata } from "next";
import "./globals.css";
import "@/styles/tokens.css";
import Providers from "./providers";
import LayoutWrapper from "@/components/layout/layoutWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased overflow-hidden">
      <body className="h-full flex flex-col bg-background text-foreground font-text transition-colors overflow-hidden">
        <Providers>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </Providers>
      </body>
    </html>
  );
}