import type { Metadata } from "next";
import "./globals.css";
import "@/styles/tokens.css";
import Providers from "./providers";
import LayoutWrapper from "@/components/layout/layoutWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased overflow-hidden" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const saved = localStorage.getItem('theme');
                const isDark = saved 
                  ? saved === 'dark'
                  : window.matchMedia('(prefers-color-scheme: dark)').matches;
                
                if (isDark) {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body className="h-full flex flex-col bg-white dark:bg-[#171b1d] text-foreground font-text transition-colors overflow-hidden">
        <Providers>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </Providers>
      </body>
    </html>
  );
}